name: WoodDye
version: 1.1.0
description: No plugin does wood more good!  Stain your wood with dyes - bleach it with bone meal!
author: SableDnah
website: http://dev.bukkit.org/server-mods/WoodDye/

main: me.sablednah.wooddye.WoodDye
softdepend: [ Spout ]

commands:
    wooddye:
        description: Root command for all  WoodDye Commands.
        usage: /<command> [reload]

permissions:
    wooddye.*:
        description: Players with this node have all WoodDye permissions.
        default: op
        children:
            wooddye.reload: true
        
    wooddye.reload:
        description: Players with this node can use reload command.
        default: op
